### ISSUE TITLE
Wrong osvers in Crypt-OpenSSL-RSA.yml

### ISSUE THREAD

**Issue by Exchizz** [eserte/srezic-cpan-distroprefs#1]
Hi,

I couldn't get CPAN to use Crypt-OpenSSL-RSA.yml because "osvers: '^4\.(8|9)\.0-'" does not match my perl-version.

I replaced "osvers: '^4\.(8|9)\.0-'" with "osvers: '3\.16\.0'" and it worked.

I obtained 3.1.6.0 from perl -V | grep -i osver
\Mathias

**Comment by eserte** [comment]
The correct check would be against the openssl version. Unfortunately, the cpan distroprefs schema is limited and does not allow this. So I use the osvers as a "proxy" match. This is at least valid for Debian: Debian/stretch (osvers >= 4.8.0) comes with openssl 1.1.0 and needs the patch, while Debian/jessie (osvers == 3.16.0) or Ubuntu 16.04 (osvers == 4.4.0) or CentOS6 (osvers < 3) do not need the patch. This is all Linux what I am running, so the distroprefs file works for me.

Can you tell me what kind of Linux is your system? Is it one of the mentioned, or a different one? Maybe there's something else in Config.pm which can be used for matching (myuname or so).

**Comment by Exchizz** [comment]
I'm using Ubuntu 16.04, kernel 4.10.0-42-generic and I needed the patch.

**Comment by eserte** [comment]
Strange. I have a test ubuntu 16.04 system which has only openssl 1.0.2g installed and the module works without patching here. Maybe you have something unusual in your sources.list or have installed openssl from other sources? What's the output of `apt-cache policy libssl-dev openssl`?

**Comment by eserte** [comment]
I don't think I can do anything about it --- your suggestion would be wrong on other systems (i.e. debian/jessie has osvers=3.16.0, but does not need the patch, and I don't need the match on my Ubuntu 16.04 VM). It's probably best if you just create your own distroprefs file matching your needs.
